### ISSUE TITLE
Merge in changes from Quamotion/DiscUtils

### ISSUE THREAD

**Issue by LordMike** [DiscUtils/DiscUtils#1]
@qmfrederik

**Comment by qmfrederik** [comment]
Thx!

Regarding the other comment, do you think it would make sense we move the Quamotion/DiscUtils GitHub project here? It would have the advantage of:
- Tracking history (PRs & others)
- Redirects (that repo seems to get some traffic and I'd be more than happy to redirect it here)

**Comment by LordMike** [comment]
Sure. I forgot to suggest that, but I had the thought :)

**Comment by qmfrederik** [comment]
OK - shall we go ahead with this then? It would deleting/moving the DiscUtils/DiscUtils repo so I can move it here, so I'll let you take care of the delete/move part, just so that I don't mess up your plans :)

**Comment by LordMike** [comment]
Well - we'll have to chose. Either we merge stuff from your repo into this one, and keep the work I've done with regards to splitting up - or we use your repo and somehow re-apply changes that allow it to be split.

I'm most in favor of the first, as I think the latter would require just as much work as I originally put into the splitting (due to the sheer amount of renaming and moving of files, reformatting all code, and then changes that make stuff work in a split setup - all preventing us from a simple "apply changes").

**Comment by qmfrederik** [comment]
@LordMike So I realized I'm a bit slower than I want to be on the DiscUtils stuff, so let's go ahead as you propose - keep this repo and merge the changes from the Quamotion repo over.
