### ISSUE TITLE
How To Reference?

### ISSUE THREAD

**Issue by mfu2002** [DiscUtils/DiscUtils#102]
This might be because I am new to C# but I cannot figure out **how to reference the new DiscUtils** to my current project.  It says to call the DiscUtils.Setup.RegisterAssembly(Assembly), but first I need to add DiscUtils namespace to my project to call that method, and I cannot find any .dll or similar file extensions to reference it with. 

Thanks,
Faisal K.

**Comment by zivillian** [comment]
Can you tell us some details about your Environment?
- OS (Linux, MacOS, Windows)
- Framework (net20, net40, netstandard)
- Tooling (VS2013, VS2015, VS2017, VS Code, other)

**Comment by LordMike** [comment]
I would imagine it's a case of not installing the package using Nuget. 

The package is here: https://www.nuget.org/packages/Discutils/0.13.0-alpha (note that multiple sub-packages exist, but this one will pull them all in).

**Comment by mfu2002** [comment]
Thank you. That was the problem. I was not installing the package using Nuget.
