### ISSUE TITLE
xfs v5 has issue

### ISSUE THREAD

**Issue by tick-guo** [DiscUtils/DiscUtils#109]
v5 ,can not read correctly.
and
v4, can browse file names , but can not open correctly.

hope to solve it

**Comment by travist13** [comment]
Hi, @zivillian fixed this issue with this PR: https://github.com/DiscUtils/DiscUtils/pull/129

My images work now.

Cheers!
Travis

**Comment by tick-guo** [comment]
It looks like it's been dealt with.
