### ISSUE TITLE
How to list files in NTFS from an exist vmdk files?

### ISSUE THREAD

**Issue by OlingCat** [DiscUtils/DiscUtils#110]
I tried code in #80 and it works. And now I have a file named `container.vmdk`, it contains a NTFS, which contains a file named `Test.dll` in directory `Root`.

So I wrote code as below to list all the files in a *exist* vmdk file:
```
static void ListFiles()
{
    string fileName = System.IO.Path.GetDirectoryName(
                            System.Reflection.Assembly.GetExecutingAssembly().Location) + @"\container.VMDK";
    Disk destDisk = new Disk(fileName, FileAccess.ReadWrite);
    NtfsFileSystem destNtfs = new NtfsFileSystem(destDisk.Content);
    string[] strs = destNtfs.GetFiles("Root");
    foreach (string s in strs)
    {
        Console.WriteLine(s);
    }
}
```

But it will cause `System.DivideByZeroException`. What did I missed?

**Comment by OlingCat** [comment]
@paulallenbright Any suggest?

**Comment by zivillian** [comment]
Can you post the Stacktrace of the DivideByZeroException?

**Comment by drebrez** [comment]
@OlingCat does the vmdk disk also contains partitions?

**Comment by OlingCat** [comment]
Thank you guys, this problem solved according https://github.com/DiscUtils/DiscUtils/blob/master/Utilities/NTFSDump/Program.cs
The key is BlockCacheStream
