### ISSUE TITLE
Using SparseStream.Pump to only copy data to another file?

### ISSUE THREAD

**Issue by EricZimmerman** [DiscUtils/DiscUtils#123]
i have a SparseStream object and can see the extents. When i do something like call StreamExtent.Blocks and iterate over the collection, i can see where the data starts and its length.

it appears SparseStream.Pump can be used to copy only the actual data out vs all leading 0s for example, so i tried this:

```csharp
using (var dest = File.Open(fileDest, FileMode.OpenOrCreate, FileAccess.Write))
{
	fileStream.Seek(0, SeekOrigin.Begin);
	loggerConsole.Trace($"Copying '{sourceFile.FullFilePath}'");
 //   fileStream.CopyTo(dest);

	SparseStream.Pump(fileStream,dest,Sizes.Sector);

}
```

but i still end up with all the leading 0s in the dest stream (the same if i use fileStream.CopyTo(dest)). 

is there some trick to only get the actual data from fileStream into a new file on disk? it looks like RunSparse is the default when Pump is called, but I am not sure if I have to do something with converting dest in my example to a SparseStream as well.

I essentially am trying, for example, to copy only the data portion of the $J ADS to a new file. i have $J open as a SparseStream already, so its just a matter of seeing how to save the non-Sparse areas to disk.

thanks!

**Comment by LordMike** [comment]
Semtantically, what you want is a Stream covering the $DATA portion for "$J", which would then ignore the Sparse Stream semantics, and just provide the actual data in order.

It's probably not exposed since it would be confusing or "wrong" to provide this, since you need to reconstruct the Sparse Stream to have the original data. I'm pretty sure it isn't possible today.

However. Maybe an option can be added to Open, like "Unbuffered", that would be "IgnoreSparse" - which would do this.

**Comment by LordMike** [comment]
Note: PumpStream will at all times copy the zeroes out: either it does a regular Stream copy, or it sees that it's working with SparseStreams, and only reads out extents. In the Sparse case, it still seeks in the [destination stream here](https://github.com/DiscUtils/DiscUtils/blob/17988ab7ecd6592b51db30c1f50d8fe89b508297/Library/DiscUtils.Streams/StreamPump.cs#L217).

Wouldn't you, @EricZimmerman, be able to read out the Extents of the SparseStream, like it does [here](https://github.com/DiscUtils/DiscUtils/blob/17988ab7ecd6592b51db30c1f50d8fe89b508297/Library/DiscUtils.Streams/StreamPump.cs#L199) ?

**Comment by EricZimmerman** [comment]
yes, and this was going to be my next approach, but I wanted to ask to make sure I wasn't missing something. 

this is a great project by the way! thanks for maintaining it
