### ISSUE TITLE
XFS inode btree extent magic check fails for opening those file streams in XFS v5 file systems

### ISSUE THREAD

**Issue by travist13** [DiscUtils/DiscUtils#134]
Hi @zivillian ,

The image I was using was a RHEL 7.5 XFS vhd. Here is where it is failing when I try to open this file from the xfs file system:

Xfs.BTreeExtentRoot.cs LN94
> if (child.Magic != BTreeExtentHeader.BtreeMagic)
> {
> throw new IOException("invalid btree directory magic");
> }

>child.Magic = 1112359219 (0x424d4133)
>BTreeExtentHeader.BtreeMagic = 1112359248 (0x424d4150)

I did some quick research and I found this spec:

>http://ftp.ntu.edu.tw/linux/utils/fs/xfs/docs/xfs_filesystem_structure.pdf

On page 11/168 it shows these two magic values which match to the ones above:

![image](https://user-images.githubusercontent.com/13336825/52604330-4bacf200-2e1f-11e9-8a78-83138997f280.png)

Looking at section 15.2 of the spec above, it mentions a different magic number but it is not clear to me what differences they have:

> The magic number for a BMBT block is “BMAP” (0x424d4150). On a v5 filesystem, this is “BMA3” (0x424d4133).

This has something to do with how the block mappings are set I think. Can you help?

Thanks,
Travis

**Comment by zivillian** [comment]
As far as I can tell XFSv5 also changed the Magic for b+trees. Sadly I've missed this in #129. I'll try to update the test data, to also include btree extents.

Where can I get this image, and which exact file did you try to open?

**Comment by travist13** [comment]
This was a Redhat 7.5 image. You should be able to get an equivalent image here:

>Version          : 7.5.2018081519
Skus             : 7.5
Offer            : RHEL
PublisherName    : RedHat

As for the file I was targeting from /var/log/messages-<date> (e.g. var\log\messages-20190210), only the latest file was a btree extents file and threw the IO exception. I found one more file that fails '/var/log/waagent.log'. This log is coming from an azure VM with the azure agent. Creating a VM in azure will should have this file after it provisions. These were the only two files that I found but I wasn't able to do an extensive search yet. Most files are not btree extents that I saw.

**Comment by zivillian** [comment]
@LordMike can you postpone the release, so that I've a chance to get this fixed?

**Comment by LordMike** [comment]
It's already out. But not to worry, we'll just push again.. We can make many releases :)

If possible, can you embed a binary file with an XFS filesystem that exhibits this behaviour, that fails; which will then succeed in the fix?.. I've added a test for EXT4 that does this, where I store it in gz format to save space.. I've also marked `.gz` as binary in Gitattributes, so hopefully it shouldn't mess up too bad.

See how I've done the EXT test for pointers.
