### ISSUE TITLE
DetectFileSystems(...) fails on NTFS volumes "XFS Features not supported"

### ISSUE THREAD

**Issue by travist13** [DiscUtils/DiscUtils#135]
Hi @zivillian ,

It looks like the XFS V5 change has an issue when trying to read a windows (NTFS) vhd. Can you take a look?

Exception location:

            if (SbVersion >= (ushort)VersionFlags.Version5)
            {
                CompatibleFeatures = EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xD0);
                ReadOnlyCompatibleFeatures = (ReadOnlyCompatibleFeatures)EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xD4);
                IncompatibleFeatures = (IncompatibleFeatures)EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xD8);
                LogIncompatibleFeatures = EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xDC);
                Crc = EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xE0);
                SparseInodeAlignment = EndianUtilities.ToUInt32BigEndian(buffer, offset + 0xE4);
                ProjectQuotaInode = EndianUtilities.ToUInt64BigEndian(buffer, offset + 0xE8);
                Lsn = EndianUtilities.ToInt64BigEndian(buffer, offset + 0xF0);
                MetaUuid = EndianUtilities.ToGuidBigEndian(buffer, offset + 0xF8);
                if ((IncompatibleFeatures & IncompatibleFeatures.Supported)!= IncompatibleFeatures.Supported)
                    throw new NotSupportedException("XFS Features not supported");
            }

Stack:
>	DiscUtils.Xfs.dll!DiscUtils.Xfs.SuperBlock.ReadFrom(byte[] buffer, int offset) Line 423	C#
 	DiscUtils.Xfs.dll!DiscUtils.Xfs.XfsFileSystem.Detect(System.IO.Stream stream) Line 75	C#
 	DiscUtils.Xfs.dll!DiscUtils.Xfs.FileSystemFactory.Detect(System.IO.Stream stream, DiscUtils.VolumeInfo volume) Line 34	C#
 	DiscUtils.Core.dll!DiscUtils.FileSystemManager.DoDetect(System.IO.Stream stream, DiscUtils.VolumeInfo volume) Line 115	C#
 	DiscUtils.Core.dll!DiscUtils.FileSystemManager.DetectFileSystems(DiscUtils.VolumeInfo volume) Line 82	C#
 	TravistTestVhd.exe!TravistTestVhd.Program.Main(string[] args) Line 97	C#

**Comment by zivillian** [comment]
From a first look, this should be addressed in #104

**Comment by travist13** [comment]
Yep, that looks like it would fix it. Thanks. This isn't blocking me though. So whenever this gets in is fine for me.
