### ISSUE TITLE
Ntfs: BiosParameterBlock.IsValid fails for NTFS in Microsoft Xbox One virtual filesystem

### ISSUE THREAD

**Issue by tuxuser** [DiscUtils/DiscUtils#146]
Hey

Hit a roadblock with opening an NtfsFileSystem from a virtual filesystem (similar to VHD) from Microsoft's Xbox One.

## Expected Behavior
NtfsFileSystem should be initialized without throwing __BIOS Parameter Block is invalid for an NTFS file system__.

## Current Behavior
NtfsFileSystem is throwing __BIOS Parameter Block is invalid for an NTFS file system__ because BiosParameterBlock `SignatureByte == 0x00` and not expected `0x80` value.
When setting that byte manually in the source image, parsing the filesystem works just fine!

## Possible Solution
From my current understanding, without the SignatureByte indicating a specific EBPB revision, it is still a valid filesystem, right?

Some ideas
1. Change BiosParameterBlock.IsValid to check _NTFS_ magic instead of EPBP SignatureByte?
2. Introduce a parameter to NtfsFileSystem initialization to skip checking the EPBP signature?
3. Skip SignatureByte check entirely?
4. Workaround: Does DiscUtils provide some sort of overlay-Stream that could be used to patch this single byte before feeding it to NtfsFileSystem initializer?

## Steps to Reproduce
1. Take an arbitrary NTFS filesystem image
2. Jump to NTFS BiosParameterBlock
3. Overwrite byte @ offset *0x26* with `0x00` 
4. Try to open the stream:
```cs
NtfsFileSystem fs = new NtfsFileSystem(stream);
Console.WriteLine("Hooray, I can read the stream!");
```

## Context (Environment)
- OS X: 10.14.3 Mojave
- .NET: .NET Core 2.0
- Discutils: 0.14.2-alpha and git tested

- NTFS data: Xbox One Virtual Container (XVD/XVC)

Sample Data:
__BiosParameterBlock__
```hex
00004000: 0000 004e 5446 5320 2020 2000 1001 0000  ...NTFS    .....
00004010: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00004020: 0000 0000 0000 0000 d829 0000 0000 0000  .........)......
```

## Detailed Description
https://github.com/DiscUtils/DiscUtils/blob/def40ec3611248a01227439ef2d6cea25f452375/Library/DiscUtils.Ntfs/BiosParameterBlock.cs#L194-L200

Line 196 ensures `SignatureByte 0x80` which would indicate __Extended boot signature (0x80 aka "8.0") (similar to DOS 3.4 EBPB and DOS 4.0 EBPB)__
The NTFS stream I am working with however propagates `SignatureByte 0x00`.

This leads to __BIOS Parameter Block is invalid for an NTFS file system__ when trying to initialize a NtfsFileSystem...
https://github.com/DiscUtils/DiscUtils/blob/25bdb252545511c8d83eca5b7b04105e69dd7f62/Library/DiscUtils.Ntfs/NtfsFileSystem.cs#L76-L79

**Comment by tuxuser** [comment]
Came up with following workaround:

```cs
Stream GetPatchedNtfsPartitionStream(Stream inStream)
{
    /* Workaround:
    * Wrap the NTFS filesystem stream  in a SnapshotStream to override
    * BiosParamaterBlock's SignatureByte in memory for DiscUtils to accept
    * the stream.
    *
    * See: https://github.com/DiscUtils/DiscUtils/issues/146
    */
    var snapshotStream = new DiscUtils.Streams.SnapshotStream(inStream, Ownership.None);

    snapshotStream.Snapshot();
    snapshotStream.Seek(0x26, SeekOrigin.Begin);
    snapshotStream.WriteByte(0x80);

    return snapshotStream;
}
```

Source: https://github.com/emoose/xvdtool/blob/ceb8398680889b946a74a12aa63de62351c0e22b/LibXboxOne/XVD/XvdFilesystem.cs#L41-L58

**Comment by LordMike** [comment]
@tuxuser interesting. Could you make a PR changing the BPB check to the _NTFS_ string at 0x02-0x05 ?

**Comment by EricZimmerman** [comment]
I have seen that same issue with FTK imager when the file system gets scanned when it's mounted by FDK

**Comment by tuxuser** [comment]
@LordMike PR #148 ready

**Comment by tuxuser** [comment]
Upstreamed - thanks!

**Comment by LordMike** [comment]
Well.. Thank _you_ ;)
