### ISSUE TITLE
DivideByZeroException reading (invalid?) FAT32 image

### ISSUE THREAD

**Issue by voltagex** [DiscUtils/DiscUtils#152]
```
            using (Stream stream = File.OpenRead(@"C:\Users\Adam\Desktop\fat-test.img"))
            {
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                DiscUtils.Fat.FatFileSystem fat = new FatFileSystem(stream);
                Console.WriteLine(fat.VolumeLabel);
            }
```
Throws a DivideByZeroException.

```
at DiscUtils.Fat.FatFileSystem.DetectFATType(Byte[] bpb)
at DiscUtils.Fat.FatFileSystem.Initialize(Stream data)
at DiscUtils.Fat.FatFileSystem..ctor(Stream data)
```

Was attempting to read 2019-04-08-raspbian-stretch-lite.img (https://downloads.raspberrypi.org/raspbian_lite_latest) which contains a FAT32 partition at the start of the image. Yes, DiscUtils should probably throw me out at this point, but DivideByZero isn't the exception I was expecting.

Edit: right, seeking to 0x400000h, copying to another stream and then reading from there works. I suspect I could use DiscUtils partiton functions to do this for me - but calling `new FatFileSystem` seems to seek back to 0 in the Stream, then crash. Should I raise another bug for this?

**Comment by voltagex** [comment]
Added tests - but it definitely looks like I shouldn't force-push to a branch that's being used for a PR!

**Comment by LordMike** [comment]
I think a lot of the filesystem types might seek back, and expect that their FS starts at 0 .. so that'll be a major change, unfortunately. On the other hand, all offset calculations would fail if you arbitrarily seeked around to find the start.

I would look in to using the disk partitioning features of DiscUtils to find the partition you need, and then open that as a Stream.

**Comment by voltagex** [comment]
@LordMike thanks for this. I am missing some C# knowledge then - how do I grab a segment of a Stream without doing a CopyTo?

**Comment by LordMike** [comment]
If you want to "partition" a stream (seeing only a segment of it), you'll need to wrap it in another stream that truncates it. One way to do this is by using the Partitioning systems in DiscUtils, another is if you simply know the offsets, to create a stream that translates this offset.

I think [Substream](https://github.com/DiscUtils/DiscUtils/blob/master/Library/DiscUtils.Streams/SubStream.cs) from DiscUtils does what you need.

**Comment by LordMike** [comment]
I'll merge in the change, as the bytes per sector being 0 is invalid either way. Thanks for the contribution :).
