### ISSUE TITLE
Support FS ?

### ISSUE THREAD

**Issue by slenno** [DiscUtils/DiscUtils#155]
Hi LordMike,
Does DiscUtils support the following Vhd/vhdx with the below FS:
1. ReFS
2. LVM, 
3. GPT partitioned disks
4. ext3, ext4, XFS ?

Thanks.

**Comment by LordMike** [comment]
Everything except ReFS should be covered.

**Comment by slenno** [comment]
Thanks. Is ReFS planned ?

**Comment by LordMike** [comment]
Not quite. It's a huge undertaking.
