### ISSUE TITLE
How to retrieve FAT(32) free sectors

### ISSUE THREAD

**Issue by h3x4d3c1m4l** [DiscUtils/DiscUtils#166]
Hi, I would like to implement something like 'partclone' in C#.

To make cloning really fast I would prefer to only copy sectors that are in use. I know NTFS has the $Bitmap file that contains information about which sectors are in use and which aren't but how can I do this in FAT32?

**Comment by LordMike** [comment]
FAT* systems store their [unused clusters in a special structure](https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system#Cluster_map). You'll need to identify this and then work from there. DiscUtils at some point has to read this to be able to create files, so if you can find that in DiscUtils, you can see if it's surfaced anywhere.

I'm not familiar with DiscUtils FAT* filesystem implementations.

**Comment by h3x4d3c1m4l** [comment]
Hm, not as easy as I hoped for. Thanks anyway! I'll look into it.
