### ISSUE TITLE
Physical size of vhdx file is 12 times bigger than its content

### ISSUE THREAD

**Issue by SparkyTD** [DiscUtils/DiscUtils#186]
I am integrating DiscUtils into my application, and I have noticed something very strange. First, the app creates a dynamic vhdx file with the smallest possible block size (1 MB), and formats it to NTFS. After that, it copies approx. 10000 small files on the newly created filesystem with `OpenFile(..., FileMode.Create, FileAccess.ReadWrite)`. The total size of all the files is 1.16 GB according to the windows explorer, but for some reason, the size of the vhdx file ends up being over 12 GB.

I have tried creating another vhdx with the built-in partition manager of windows, and I manually copied all 10k files on it, but the new virtual disk's size was a more reasonable 1.47 GB.

I have also tried running the Optimize-VHD powershell command on the first disk, but it did basically nothing to the 12 GB file.

This is the code that creates the vhdx file:
```
using (var stream = File.Create(path))
{
    var disk = Disk.InitializeDynamic(stream, Ownership.None, size, 1048576);
    BiosPartitionTable.Initialize(disk, WellKnownPartitionType.WindowsNtfs);

    var volumeManager = new VolumeManager(disk);
    using (var ntfs = NtfsFileSystem.Format(volumeManager.GetLogicalVolumes()[0], "DATA", new NtfsFormatOptions()))
    {
        ntfs.NtfsOptions.ShortNameCreation = ShortFileNameOption.Disabled;
        InitializeStorage(ntfs, key);
    }

    stream.Flush();
}
```

`InitializeStorage` just creates some folders and config files on the disc.

And finally, this is how I copy the files on the disk (for each file):
```
var fileStream = fileSystem.OpenFile("...filename...", FileMode.Create, FileAccess.ReadWrite);
// copy actual file contents to fileStream
fileStream.Close();
```

Am I doing something wrong, is is there some sort of issue with DiscUtils? What should I change to decrease the size of the VHDX file?

**Comment by SparkyTD** [comment]
UPDATE:
I found the source of the problem. There is a metadata file on the vhdx (created by the application) that was updated and re-written after every single copy operation. Since that file is only a couple kilobytes, I still don't understand how it managed to explode the virtual disk's size, but at least I was able to fix the problem by not rewriting that file after every operation.

**Comment by LordMike** [comment]
Do note that the VHDX file will represent a much larger disk (you didn't mention what its cap was). I'm unsure, but the NTFS allocator could be as simple as just "find the next block available after last", meaning that whatever file you wrote last, will mark the "beginning" of the next file.

In other words. If you were to write as many small files (and deleting them as you go), as the disk could hold - you'd end up maxing out the VHDX, before the NTFS allocator loops back and begins from the beginning.

**Comment by EricZimmerman** [comment]
i see this too in one of my projects. i just zip the container and the size drops way down for moving it around.
