### ISSUE TITLE
Dependency on dokan.net?

### ISSUE THREAD

**Issue by Rainmaker52** [DiscUtils/DiscUtils#187]
I'm looking at discutils to see if I could create something of a virtual filesystem with it that works cross platform.

During my research, I noticed that the Dokan.net page at https://dokan-dev.github.io/ lists discutils as one of the projects that uses it.

Is this correct? Do I need to have the dokan kernel driver installed for some of the functionality to work? If so, does discutils automatically switch to using fuse on Linux platforms?

**Comment by LordMike** [comment]
Quickly searching for Dokan in the code does not reveal any. I'm quite sure I haven't removed such a dependency when migrating to .NET Core, so I'm unsure when that feature was lost.

**Comment by Rainmaker52** [comment]
Yeah, I looked through the source and looked at nuget dependencies, but couldn't find it either.

The only mention I found was the old codeplex repo for discutils at https://archive.codeplex.com/?p=dokandiscutils.

But, you confirmed my suspicion that the statement that discutils uses or depends on dokan seems to be incorrect.

Thanks for the quick response.
