### ISSUE TITLE
Add DiscUtils.Streams package

### ISSUE THREAD

**Issue by qmfrederik** [DiscUtils/DiscUtils#19]
DiscUtils contains a lot of internal classes which allow you to consume streams - for example, there's a `SubStream` class or a `ConcatStream` class.

I need such streams from time to time in other projects, and one of the limitations has always been that those classes are marked `internal`.

Hence the suggestion is to:
- Move those classes to a `DiscUtils.Stream` project
- Make them public

@LordMike Thoughts?

**Comment by LordMike** [comment]
Do you have a listing of them?

If there are more than a few, I would consider it, else it might just be enough marking them in the base DU library as public.

**Comment by LordMike** [comment]
On the same subject (and not knowing every stream available), how big is the "market" for Stream implementations?.. I've done a number in the past, f.ex. a "PartialStream" where a set of chunks/ranges from a source stream is exposed in one continous stream (skipping hidden areas) - great for "snapshots" of sources.

**Comment by qmfrederik** [comment]
Here's a preliminary list.

Ones that seem to be of general interest:

* AligningStream
* BlockCacheStream
* CircularStream
* ConcatStream
* MirrorStream
* SnapshotStream
* SparseMemorySTream
* SparseReadOnlyWrapperStream
* SparseWrapperStream
* StripedStream
* SubStream
* ThreadSafeStream
* WrappingMappedStream
* WrappingStream
* ZeroStream

Specific to DiscUtils (I believe):
* BufferStream
* BuiltStream

I don't have hard numbers on how big the market is :) but I'm guessing anyone who is doing low level I/O will at least at some point have had the need for things like SubStream, SparseStream or ConcatStream.

Sounds like PartialStream you mentioned would be a combination of multiple SubStreams joined into one ConcatStream?

**Comment by LordMike** [comment]
So I just grabbed `StreamExtent` and moved it out. It's meddled in with `Range` and `Utilities` which might then need to be moved out themselves. It's a little more than I can do this evening :).

**Comment by qmfrederik** [comment]
No worries :). I think there's other stream-related stuff which may be interesting as well (`BigEndianDataReader` and `BigEndianDataWriter`, for example).

**Comment by zivillian** [comment]
I've created an initial version of a DiscUtils.Streams package. Please take a look and let me know if there is anything i should change or add.

I guess the next thing would be to introduce something like DiscUtils.Base where we can move Func, Utilities and such.
