### ISSUE TITLE
Publish new versions to NuGet

### ISSUE THREAD

**Issue by gfs** [DiscUtils/DiscUtils#196]
Hey Maintainers,

I'm wondering what the plan going forward is for releases.  Will future releases at some point be brought back to the NuGet feed (the latest is about a year old now) or is the MyGet feed the permanent source now?

The problem I'm having is that users who take a dependency on a library which takes a dependency on MyGet must also update its own Nuget.config to add the DiscUtils feed.  As you can imagine this isn't a great solution.

1. Is there a solution I'm unaware of you recommend that will obviate the need for those who take a dependency on a project which uses the MyGet feed version of DiscUtils to create their own Nuget.Config including discutils?
2. Will builds be coming back to Nuget at some point?
3. If so, do you have a timeframe estimate?

**Comment by daalcant** [comment]
+1 and a quick note that we could facilitate this with GitHub Actions

**Comment by LordMike** [comment]
Hi. The Nuget feed is the official one, while Myget is meant to be the feed for ci builds.

**Comment by LordMike** [comment]
If what you need is whatever is on the myget feed, then we'll just have to do a version that pushes to Nuget .. :P

As for github actions. I suppose. Currently it's running on Appveyor or something like that. The action would have to run on Windows, due to the .NET framework dependency.
