### ISSUE TITLE
Prepare CI + Publish to Nuget

### ISSUE THREAD

**Issue by LordMike** [DiscUtils/DiscUtils#2]
Appveyor is linked in, we need to set up the API key so publishing can happen.

**Comment by LordMike** [comment]
@qmfrederik could you add me to owners of the Nuget package `DiscUtils`?

**Comment by qmfrederik** [comment]
@LordMike Done! Will you publish on specific tags or publish all CI builds to NuGet?

**Comment by LordMike** [comment]
Only commits to the `nuget` branch will be published. I'm unsure how to do it by tags, this was the easiest for me :)

**Comment by LordMike** [comment]
Fixed in #16
