### ISSUE TITLE
Problem with OpenDisk: "Unable to parse path...

### ISSUE THREAD

**Issue by isential-gmbh** [DiscUtils/DiscUtils#212]
I already fail when trying to open a VHDX. I always get the following error message (translated from German):

Unhandled exception
System.IO.FileNotFoundException: "Unable to parse path 'c:\test\disk.vhdx'""

However, the VHDX exists and its name and path are correct.

Here is a test code:

```
using System;
using DiscUtils;

namespace vhdx2
{
	class Program
	{
		static void Main(string[] args)
		{
			using (VirtualDisk Vhdx = VirtualDisk.OpenDisk("c:\\test\\disk.vhdx", System.IO.FileAccess.Read))
			{
			}
		}
	}
}
```
I don't know if this is a bug related to VHDX files, I only know that the VHDX file exists, is error-free and accessible. For example the following program code works:

`DiskImageFile vhdxFile = new DiskImageFile("c:\\test\\disk.vhdx", FileAccess.Read)`

Many thanks!

René

**Comment by isential-gmbh** [comment]
OK, I'm a little further along. I had overlooked the need for initialization:

`DiscUtils.Setup.SetupHelper.RegisterAssembly(System.Reflection.Assembly.GetExecutingAssembly());`

However, when I call it

`VirtualDisk Vhdx = VirtualDisk.OpenDisk(VhdxFile, FileAccess.ReadWrite))`

I get always "null". This is independent of file access or credentials (user and password).

Now I unfortunately do not get any further. What else needs to be done to access the VHDX?

**Comment by LTRData** [comment]
The initialization should look like this:
`DiscUtils.Setup.SetupHelper.RegisterAssembly(typeof(DiscUtils.Vhdx.Disk).Assembly);`

Or, if you know it is always a vhdx format image file, simply use OpenDisk directly on DiscUtils.Vhdx.Disk class:
`VirtualDisk Vhdx = DiscUtils.Vhdx.Disk.OpenDisk(VhdxFile, FileAccess.ReadWrite);`

**Comment by isential-gmbh** [comment]
Thank you very much. Now we continue with the exploration. What is still missing is a documentation. Maybe you can put together a troop to work on it. I would like to participate in it.

Kind regards

René
