### ISSUE TITLE
Getfiles giving different file names than actual one

### ISSUE THREAD

**Issue by hnviradiya** [DiscUtils/DiscUtils#223]
I am reading files from iso file. It gives different file names than the actual ones.

What I am getting is as below.
![image](https://user-images.githubusercontent.com/12680915/103474152-fe491d80-4dc6-11eb-8c36-26277bcc58f5.png)

What actual file names are as below.
![image](https://user-images.githubusercontent.com/12680915/103474173-2c2e6200-4dc7-11eb-8215-37f3e65ca1ab.png)

Below is the package reference I am using.

`<PackageReference Include="Discutils" Version="0.15.1-ci0007" />`

**Comment by hnviradiya** [comment]
I am using following iso file.

https://s3.amazonaws.com/rds.nsrl.nist.gov/RDS/current/RDS_android.iso

**Comment by oakdemirci** [comment]
If you use UseJoilet = true, lowercase and uppercase is differentiated.
