### ISSUE TITLE
Release stable version - GitHub actions - NuGet access

### ISSUE THREAD

**Issue by qmfrederik** [DiscUtils/DiscUtils#232]
Hi @LordMike 

I would like to release a stable version of, at the very least, DiscUtils.Core and DiscUtils.Streams.
I think the core packages are quite stable by now (we haven't had major changes in the last year or so).
I want to publish a couple of packages which depend on DiscUtils as a major version, but you can't do that if you have dependencies which are marked as prerelease.
Other folks have been asking for this, too.

I'd also like to move CI over to GitHub actions. For one, travis.org is shutting down, so we'd be losing our Linux CI.

Right now, I can't do that because you own the NuGet packages, so I can't configure a NuGet access key.

Do you think you could create an organization on GitHub which owns the packages, and add me as a member of that organisation?

Thanks.

**Comment by LordMike** [comment]
Definitely. I've also been working on Github actions for other projects, where I use Github packages to distribute Nuget packages. That could be used for CI builds.

Good work on merging stuff in btw.. Haven't had a lot of time for this immense project.. :)

**Comment by LordMike** [comment]
Is .NET Framework 2.0 even necessary anymore?

**Comment by qmfrederik** [comment]
> Is .NET Framework 2.0 even necessary anymore?

I don't think so. It's 15 years old. It's unlikely a project targeting .NET 2.0 would be using a NuGet package (NuGet was released in 2010).

NET 4.6.1 went out of support this week, so .NET 4.6.2 is the oldest .NET version which is still under support.

**Comment by LordMike** [comment]
I'll clean up a little too. :)

**Comment by LordMike** [comment]
So I've:

* Introduced to build flows for Github actions, both on Windows - I seemed unable to get most tests to work on linux, although the windows nodes are significantly slower at everything .. :|
* Changed to MinVer - I find this project simpler than GitVersion
* Removed all appveyor etc.
* Github actions also publish to github packages, when pushing to `develop`.
* Added xml docs to the nuget packages

Todos:
* Make tests work on Windows nodes, possibly linux nodes (maybe we should build on both - tests work fine on my Win10 .. so maybe there are some OS differences..)
* Create nuget org with ownership of `DiscUtils.*` (needs an email :|)
* Make generic description for all packages (preferably at the bottom), saying a few words about the DU project
* Cleanup target frameworks .. I don't think net20 is needed anymore (otoh, it probably doesn't hurt, besides requiring Windows builds).. and I'm not sure if `net5.0` is necessary, when we target `netandard2.0`.. ?

You wouldn't happen to know why these tests are failing, @qmfrederik ?

**Comment by qmfrederik** [comment]
This error:

> No data is available for encoding 437. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.

Can be fixed by:

1. Adding a package reference to System.Text.Encoding.CodePages
2. Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

**Comment by qmfrederik** [comment]
> Changed to MinVer - I find this project simpler than GitVersion

If you don't have a strong preference, what about https://github.com/dotnet/nerdbank.gitversioning? It's a .NET Foundation project, I use it in all my projects, and the most recent version has no dependency on git or libgit2 (nbgv ships with a managed Git implementation).

**Comment by LordMike** [comment]
> > Changed to MinVer - I find this project simpler than GitVersion
> 
> If you don't have a strong preference, what about https://github.com/dotnet/nerdbank.gitversioning? It's a .NET Foundation project, I use it in all my projects, and the most recent version has no dependency on git or libgit2 (nbgv ships with a managed Git implementation).

As long as there is no native dependency (that's bugged me a lot), and that it's fast.. One issue I had with one of the gitversion tools was that it recalculated the version for each project in a solution (hence my tendency to calculate versioning once and apply it by includes).. Minver has yet to show the same slowness. 

> This error:
> 
> > No data is available for encoding 437. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
> 
> Can be fixed by:
> 
> 1. Adding a package reference to System.Text.Encoding.CodePages
> 2. Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);

I tried including some code that runs on the start of the tests, that do the above - but with no effect. So either it's not running (it does locally), or it doesn't work -- but it should work, so the conclusion is likely that it doesn't run.

(Also note we have `EncodingHelper` that does that. :)

**Comment by qmfrederik** [comment]
You can fix most of the encoding errors by initializing the encoder in the static constructor of the FatFileSystem class. I've opened a PR for that.

As for nbgv:
- A lot of work has been done the mitigate the perf impact. Version height is calculated only once per build, and cached. For most projects, the cost should be in the ~100ms range, or less. See https://github.com/dotnet/Nerdbank.GitVersioning/issues/114 for more details
- The git implementation is entirely managed since the 3.4 release, so there's no native dependency (git or libgit2).

**Comment by AArnott** [comment]
> Version height is calculated only once per build, and cached

It's calculated once per project. To get once per build, you have to opt-in since you're deciding what scope of projects to assume will always share the same version. It's very simple to opt in. Instructions are here: https://github.com/dotnet/Nerdbank.GitVersioning/blob/master/doc/msbuild.md#reducing-getbuildversion-invocations

But as @qmfrederik says, even without the opt-in, NB.GV is _very_ fast now.

**Comment by qmfrederik** [comment]
@LordMike The GitHub workflow you have on your branch look like a good start. Is there anything else you want to add before merging that into develop?

**Comment by LordMike** [comment]
I don't think so - I just haven't found time for it..
You could try merging it in - then I'll see if I can't make that Nuget org.

Mvh.
Michael

**Comment by qmfrederik** [comment]
@LordMike I updated the CI script a bit. Pushing to NuGet from tags fails, looks like the `NUGET_KEY` is incorrect or insufficient permissions.

Could you have a look? Alternatively, I can generate the NuGet key myself if you create a NuGet org or grant the quamotion org or my personal account access to the DiscUtils packages.

**Comment by LordMike** [comment]
@qmfrederik what's your Nuget username?

quamotion is an organization - so I cannot add it as an admin of the new DiscUtils org.

**Comment by LordMike** [comment]
I have:

- Created a new api key for DiscUtils - I must have deleted the one I made.. your action now succeeded after a retry
- Created an org
- @qmfrederik is pending membership
- Transferred all _32_ packages to DiscUtils org
- Removed _all_ other owners of the packages
- Created yet another api key in the org, and added that to Github secrets

Should all be set now.

**Comment by qmfrederik** [comment]
@LordMike Awesome, thanks!

I took the time to unlist and deprecate all Quamotion.DiscUtils.* packages on NuGet, and mark the DiscUtils.* packages as the equivalent.

I got e-mail from NuGet about the package ownership changes, but didn't get an invitation for the DiscUtils org. Can you try removing and adding my account once more?

**Comment by LordMike** [comment]
I meant to say that I was still "pending" your username... but the package you sent to the organization revealed the username (which coincidentally was identical to Github), so I've now added you as a member.. 

Now it is no longer "pending" from my side :)

**Comment by qmfrederik** [comment]
Awesome, thanks! All good now ;-).
