### ISSUE TITLE
how to write and delete file in  existing VMDK  ?

### ISSUE THREAD

**Issue by shan333chao** [DiscUtils/DiscUtils#259]
The following code  is my VMDK file operating  .   

VMDK could not to be write file or delete a file by my function,

 it is no permission to write  in VMDK partition, but reading a file  is fine in  VMDK partition

how to operate delete and modify a file in VMDK partition

```
public void ImportFile(String vmdkPath, String DestinationFile) {
            String tokenFile = @"\\data\com.xxxx.xxxx.xx\shared_prefs\xmlfile.xml";
            VolumeManager volMgr = new VolumeManager();
            using VirtualDisk disk = VirtualDisk.OpenDisk(vmdkPath, FileAccess.ReadWrite);
            volMgr.AddDisk(disk);
            var volumes = volMgr.GetLogicalVolumes();
            var tokenVolume = volumes[1].PhysicalVolume;
            using var stream = tokenVolume.Partition.Open();
            using ExtFileSystem extFs = new ExtFileSystem(stream);
            bool isExist = extFs.FileExists(tokenFile);
            if (isExist)
            {
                extFs.DeleteFile(tokenFile);
            }
            var destBytes = File.ReadAllBytes(DestinationFile);
            using Stream bootStream = extFs.OpenFile(tokenFile, FileMode.Create, FileAccess.Write);
            bootStream.Write(destBytes, 0, destBytes.Length);
}
```

**Comment by LTRData** [comment]
DiscUtils can modify VMDK images, you can add and remove partitions etc and you can edit file systems within the images provided DiscUtils supports reading and writing that particular file system. In the case of Ext file systems, DiscUtils only supports reading them, not modifying them.


I have sometimes worked around that by finding clusters allocated by a file and modified data in them but that is tricky, risky and does not work for example to delete files.

**Comment by shan333chao** [comment]
Thanks
