### ISSUE TITLE
Strange behavior when trying to copy MAC timestamp from NTFS using RawCopy

### ISSUE THREAD

**Issue by kmahyyg** [DiscUtils/DiscUtils#262]
Using DiscUtils to get FileInfo:

```cs
    public static DiscFileInfo GetRawFileInfo(string path)
    {
      if (!Helper.IsAdministrator())
        throw new UnauthorizedAccessException("Administrator privileges not found! Cannot get raw file info!");
      if (!RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
      {
        Log.Warning("Raw disk reads not supported on non-Windows platforms. Returning null!");
        return (DiscFileInfo) null;
      }
      (string str1, string str2) = Helper.VerifyFileSystemOpen(path);
      return Helper.FileSystems[str1].GetFileInfo(str2);
    }
```

GetFileInfo finally goes to `new DiskFileInfo(NtfsFileSystem, "C:\\$$MFT")`

Then I tried to copy metadata to destination file:

```cs
string dst = "E:\\TempFolder\\aabb.bin";
f.FileInfo.CopyTo(dst);
```

It just kept telling me:

![CleanShot 2022-10-11 at 12 05 50](https://user-images.githubusercontent.com/16604643/194994815-90180b84-5a09-4529-9158-e5a9677f7890.png)

But this file actually exists:

![CleanShot 2022-10-11 at 12 06 32](https://user-images.githubusercontent.com/16604643/194994873-2e2d640e-32d5-4a04-9c94-fb3e3ef0b5f1.png)

So I guess `FileInfo.CopyTo()` should not be used in this way or there is a bug here?

BTW, Please write some detailed documentation about this library, the documentation of this library is really a nightmare.

**Comment by LTRData** [comment]
The `CopyTo` method copies a file to a new location, it does not only copy metadata. It only works within the same file system and the target path is relative to the root of that file system, you cannot use drive letters or any other way to refer to another file system. The method is implemented by calling `CopyFile` method on the file system object.
