### ISSUE TITLE
Fat32 .img files

### ISSUE THREAD

**Issue by Yazwh0** [DiscUtils/DiscUtils#271]
I know this is a long shot, but I need to be able to create .img files for fat32 images. Specifically for sdcard images.

I've forked the code, and can now force a Fat32 image regardless of size. But exporting that directly to a file appears to be corrupt. So I assume I need to wrap it in some structure so they can be read.

I dont suppose anyone has achieved such a feet?

**Comment by LTRData** [comment]
Can you please explain the steps more detailed? In particular, what exactly is "exporting directly to a file"?

If you have not tried already, you should be able to create a new image file using for example `File.OpenWrite` to get a `FileStream` and then pass that steam to the method in FAT32 library that formats the file system.

**Comment by Yazwh0** [comment]
I think I was too quick off the mark on this, apologies. Will close and reconsider.
