### ISSUE TITLE
Thread safety?

### ISSUE THREAD

**Issue by picrap** [DiscUtils/DiscUtils#29]
Hi,

how safe are the filesystems, suchs as `NtfsFileSystem`?
I get corruptions when using it and suspect something like multi-threading problem.

**Comment by LordMike** [comment]
I haven't developed the things myself, but I would strongly suspect that they're _not_ thread safe.

Your experience is a strong indicator in this direction.

**Comment by picrap** [comment]
This is confirmed: there is no multithread support.
Also, why did you setup this project, which appears to be very similar to the original (just curious)? It's not even a fork in the git sense, so I don't see the point of this organisation.
(And I found you because you released them as Nuget packages, which is a very good idea!)

**Comment by LordMike** [comment]
The project lacked some important updates (splitting up, .net core support, nuget packages ..), so I went ahead and did it. But my deep knowledge of the project is limited... :)
