### ISSUE TITLE
Rename packages to DiscUtils.*

### ISSUE THREAD

**Issue by LordMike** [DiscUtils/DiscUtils#3]
Necessary for #2

**Comment by LordMike** [comment]
@qmfrederik regarding naming. I'm thinking this (since we've acquired the DiscUtils nuget package):

We rename all `LordMike.DiscUtils.*` packages to a plain `DiscUtils.*` equivalent. This however means that the base package, DiscUtils will be a base library that isn't very useful. 

We could do the following though (with the new naming):
* `DiscUtils` becomes `DiscUtils.Core`
* `DiscUtils.Complete` becomes `DiscUtils`

How's that?

**Comment by qmfrederik** [comment]
@LordMike Sounds good to me! It will annoy some people who are on older NuGet versions (the versions which don't have transitive dependencies), but long term, this sounds like the winning strategy to me.

**Comment by LordMike** [comment]
We could jump a major version, so instead of 0.12 or whatever, we go to 1.0.
