### ISSUE TITLE
Squash history

### ISSUE THREAD

**Issue by LordMike** [DiscUtils/DiscUtils#4]
@qmfrederik you mentioned being unhappy about the history (a number of repeated commit messages).. I normally work like that (smaller commits), so it's a side effect of that. But if you find some larger parts that you'd like to put under one commit, go ahead and then force push.

**Comment by qmfrederik** [comment]
ok - let me see if I can create a branch, squash commits and if we're happy, I'll force push that to master.

**Comment by LordMike** [comment]
Note that I've completed issue #3, so you should work from those commits.
