### ISSUE TITLE
how to open help file i can not find the  'HelpContentSetup.msha'  

### ISSUE THREAD

**Issue by wangxin5355** [DiscUtils/DiscUtils#54]
echo 1. Run this batch file as Administrator
echo 2. Select 'Install content from disk'
echo 3. Select the file 'HelpContentSetup.msha' from this folder
echo 4. Select 'Add' for 'DiscUtils Class Library'
echo 5. Click 'Update'
echo 6. Confirm you want to proceed

i can not find the 'HelpContentSetup.msha'  in help folder

**Comment by LordMike** [comment]
Hi @wangxin5355,

If you're talking about the details in [this folder](https://github.com/DiscUtils/DiscUtils/tree/3b5cc2b833f0f12ccaf44469f439e4bc7391bc17/Help), I'm afraid they're probably grossly outdated. I'll have them removed as soon as possible.

Mike.
