### ISSUE TITLE
Announcement: third-party exFAT support

### ISSUE THREAD

**Issue by picrap** [DiscUtils/DiscUtils#68]
Hi there,

I requested it in issue #67, and since the answer did not come, I started to implement an exFAT support for DiscUtils.
The project `ExFat` (original name isn't it?) is now live and I released a Nuget package.
* [NuGet package here](https://www.nuget.org/packages/ExFat.DiscUtils)
* [GitHub project here](https://github.com/picrap/ExFat)

At the moment, the package requires prior explicit installation of `DiscUtils.Core` (help welcome to solve this).

The project is very young (one week at the moment), all features are implemented, but bugs can still occur. All testers are welcome (and of course, issue tracker is available to everyone, I'll be as responsive as possible)!

**Comment by LordMike** [comment]
I'm unsure - do you wish to include your code in DiscUtils?

**Comment by picrap** [comment]
I don't think this is necessary, no.

**Comment by LordMike** [comment]
Very well.

**Comment by drebrez** [comment]
@picrap FYI: Microsoft just released the exFAT file system specification:

https://docs.microsoft.com/it-it/windows/win32/fileio/exfat-specification
