### ISSUE TITLE
New Feature Request - Encase e01 format

### ISSUE THREAD

**Issue by paulallenbright** [DiscUtils/DiscUtils#76]
Would you please give consideration to adding this format to this library.   Thanks so much for all the hard work put into this so far.

http://www.forensicsware.com/blog/e01-file-format.html

**Comment by LordMike** [comment]
The library is not in active development - but if you have the time to add it, you're more than welcome :).

See #5 .

**Comment by paulallenbright** [comment]
sorry this is product is new to me... so still learning all that is in it..  let me check out how EWF is implemented...  thanks so much

**Comment by paulallenbright** [comment]
Ok I looked into the downloaded Library folder .. not seeing this:

Library/DiscUtils.Ewf/DiskImageFile.cs

I see the folders in alphabetical order... no DiscUtils.Ewf...    I just downloaded the library in the full zip download..   Guess I've missed something...

        /DiskUtils.Ext
        /DiskUtils.Fat
        etc...

**Comment by LordMike** [comment]
It does somewhat. So the big part of actually porting the code to Dotnet core and splitting it into subprojects has been done. Now it's purely maintenance.

**Comment by paulallenbright** [comment]
If you need a tester.  😀
