### ISSUE TITLE
Example Code VMDK - This is not an Issue

### ISSUE THREAD

**Issue by paulallenbright** [DiscUtils/DiscUtils#80]
If anyone is interest here is sample code for creating a VMDK and then using the vmware mounter to view it.

Vmware mounter:

https://my.vmware.com/group/vmware/details?downloadGroup=VSP510-VDDK-514&productId=284

To Mount the Container:

Vmware-mount.exe  v:  ContainerFile.VMDK

To Un-Mount the container :

vmware-mount.exe /f v:

Source Code:

  static void BuildNtfsVmdkFile()
  {  

            long diskSize = 30 * 1024 * 1024; // 30MB
            
            string sourceFilePath = Directory.GetFiles(@"D:\{Some TestData dir}").First();
            
           if ( !File.Exists(sourceFilePath) ) Console.WriteLine($"WARNING SOURCE FILE does not exist: {sourceFilePath}");
            
            Console.WriteLine($"sourceFilePath: {sourceFilePath}");
            string destinationPath = @"\Root\Test.dll";
            Console.WriteLine($"destinationPath: {destinationPath}");
            string createDirectoryName = "Root";

            string fileName = System.IO.Path.GetDirectoryName(
                                  System.Reflection.Assembly.GetExecutingAssembly().Location) + @"\container.VMDK";

            if (File.Exists(fileName)) File.Delete(fileName);
            
            try
            {
                DiscUtils.Vmdk.Disk destDisk = DiscUtils.Vmdk.Disk.Initialize( fileName, diskSize, DiskCreateType.Vmfs);
             
                // Partition the new disk with a single NTFS partition
                BiosPartitionTable.Initialize(destDisk, WellKnownPartitionType.WindowsNtfs);
                VolumeManager volMgr = new VolumeManager(destDisk);

                string label = "NTFS Volume Label";

                using (NtfsFileSystem destNtfs = NtfsFileSystem.Format(volMgr.GetLogicalVolumes()[0], label, new NtfsFormatOptions()))
                {
                    destNtfs.NtfsOptions.ShortNameCreation = ShortFileNameOption.Disabled;
                    destNtfs.CreateDirectory(createDirectoryName);

                    try
                    {
                        using (Stream source = new FileStream(sourceFilePath, FileMode.Open, FileAccess.Read))
                        {
                            using (Stream dest =
                                destNtfs.OpenFile(@destinationPath, FileMode.Create, FileAccess.ReadWrite))
                                source.CopyTo(dest);

                            //get source file attributes 
                            System.IO.FileInfo sourceFileInfo = new System.IO.FileInfo(sourceFilePath);
                            Console.WriteLine($"Source file CreateTime {sourceFileInfo.CreationTime}");

                            //set destination file dates to source utc dates
                            destNtfs.SetCreationTimeUtc(destinationPath, sourceFileInfo.CreationTimeUtc);
                            destNtfs.SetLastWriteTimeUtc(destinationPath, sourceFileInfo.LastWriteTimeUtc);
                            destNtfs.SetLastAccessTimeUtc(destinationPath, sourceFileInfo.LastAccessTimeUtc);

                        }
                    }
                    catch (Exception e)
                    {
                        Console.WriteLine($"Copy Exception Catch: {e}");
                    }
                }

            }
            catch (Exception e)
            {
                Console.WriteLine($"Format Exception Catch: {e}");
            }
        }

**Comment by rdavisunr** [comment]
@paulallenbright - just wanted to thank you for this contribution. DiscUtils is pretty short on example code and your post was a huge time saver in that regard. Thanks!
